- areanm
- year
- Incidence
- Lower CI 95.0 limit
- Upper CI 95.0 limit
- Lower CI 99.8 limit
- Upper CI 99.8 limit
- count
- Denominator
- latitude
- longitude
- t2m_1
- t2m_2
- t2m_3
- t2m_4
- t2m_5
- t2m_6
- t2m_7
- t2m_8
- t2m_9
- t2m_10
- t2m_11
- t2m_12
- spec_humidity_1
- spec_humidity_2
- spec_humidity_3
- spec_humidity_4
- spec_humidity_5
- spec_humidity_6
- spec_humidity_7
- spec_humidity_8
- spec_humidity_9
- spec_humidity_10
- spec_humidity_11
- spec_humidity_12
- rel_humidity_1
- rel_humidity_2
- rel_humidity_3
- rel_humidity_4
- rel_humidity_5
- rel_humidity_6
- rel_humidity_7
- rel_humidity_8
- rel_humidity_9
- rel_humidity_10
- rel_humidity_11
- rel_humidity_12
- src_1
- src_2
- src_3
- src_4
- src_5
- src_6
- src_7
- src_8
- src_9
- src_10
- src_11
- src_12
- sp_1
- sp_2
- sp_3
- sp_4
- sp_5
- sp_6
- sp_7
- sp_8
- sp_9
- sp_10
- sp_11
- sp_12
- tp_1
- tp_2
- tp_3
- tp_4
- tp_5
- tp_6
- tp_7
- tp_8
- tp_9
- tp_10
- tp_11
- tp_12
- lai_hv_1
- lai_hv_2
- lai_hv_3
- lai_hv_4
- lai_hv_5
- lai_hv_6
- lai_hv_7
- lai_hv_8
- lai_hv_9
- lai_hv_10
- lai_hv_11
- lai_hv_12
- lai_lv_1
- lai_lv_2
- lai_lv_3
- lai_lv_4
- lai_lv_5
- lai_lv_6
- lai_lv_7
- lai_lv_8
- lai_lv_9
- lai_lv_10
- lai_lv_11
- lai_lv_12
- avg_elevation_m
- mean_tree_cover_pct
- pct_wooded
- tick_pred
- tick_std
- 5_to_14y_fraction
- 50_to_65y_fraction
- roe_deer_record_count
- red_deer_record_count
- chinese_water_deer_record_count
- wood_mice_record_count
- bank_voles_record_count
- blackbird_record_count
